name: News Scraping Workflow

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours (UTC time)
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  scraping-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Vercel API to scrape news
        run: |
          # Use curl to send a GET request to the Vercel API endpoint
          curl -X GET "https://flask-news-scraper.vercel.app/scrape"
      
      - name: Commit and push changes to news.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add news.json
          git commit -m "Update news.json with scraped news"
          git push
        env:
          # Set GitHub token to authenticate the push
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
