name: Scrape News Every 12 Hours

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Trigger Vercel API to scrape news
      run: |
        echo "Triggering Vercel API to scrape news..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape")
        echo "Vercel Response: $response"
