name: Scrape News Feeds

on:
  schedule:
    - cron: "0 4 * * *"   # Business at 6:00 AM CAT
    - cron: "30 4 * * *"  # Sport at 6:30 AM CAT
    - cron: "50 4 * * *"  # Local at 6:50 AM CAT
    - cron: "0 6,18 * * *" # Herald at 8:00 AM & 8:00 PM CAT (UTC -2)
    - cron: "15 6,18 * * *" # Chronicle at 8:15 AM & 8:15 PM CAT (UTC -2)
    - cron: "30 6,18 * * *" # NewZimbabwe at 8:30 AM & 8:30 PM CAT (UTC -2)
    - cron: "45 6,18 * * *" # ZimEye at 8:45 AM & 8:45 PM CAT (UTC -2)
  workflow_dispatch:

jobs:
  business-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape Business Category
      run: |
        echo "Scraping Business category..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/category/business")
        echo "Vercel Response: $response"

  sport-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape Sport Category
      run: |
        echo "Scraping Sport category..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/category/sport")
        echo "Vercel Response: $response"

  local-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape Local Category
      run: |
        echo "Scraping Local category..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/category/local")
        echo "Vercel Response: $response"

  herald-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape Herald News
      run: |
        echo "Scraping Herald news..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/herald")
        echo "Vercel Response: $response"

  chronicle-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape Chronicle News
      run: |
        echo "Scraping Chronicle news..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/chronicle")
        echo "Vercel Response: $response"

  newzimbabwe-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape NewZimbabwe News
      run: |
        echo "Scraping NewZimbabwe news..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/newzimbabwe")
        echo "Vercel Response: $response"

  zimeye-scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scrape ZimEye News
      run: |
        echo "Scraping ZimEye news..."
        response=$(curl -X GET "https://flask-news-scraper.vercel.app/scrape/zimeye")
        echo "Vercel Response: $response"
